apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: springboot-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/madhavan0702/dev-madhavan.git
    targetRevision: HEAD
    path: mavenpr
  destination:
    server: https://kubernetes.default.svc
    namespace: dev-madhavan
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
