apiVersion: batch/v1
kind: Job
metadata:
  name: cpu-stress
spec:
  template:
    spec:
      containers:
      - name: stress
        image: polinux/stress
        command: ["stress"]
        args: ["--cpu", "2", "--timeout", "600"]
      restartPolicy: Never
  backoffLimit: 0

