# Create a custom PrometheusRule YAML file
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: custom-rules
spec:
  groups:
  - name: custom-alerts
    rules:
    - alert: HighPodCPU
      expr: sum(rate(container_cpu_usage_seconds_total{container!="", pod!=""}[1m])) > 0.5
      for: 1m
      labels:
        severity: warning
      annotations:
        description: "High CPU usage detected"
